name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ dc3fdc12ee5eeecc181777f7352878ab }}
          TIMEZONE: Asia/Seoul
